# Generated by Django 3.2.6 on 2021-08-10 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='information',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='securityquestions',
            old_name='user_id',
            new_name='user',
        ),
    ]
