# Generated by Django 3.2.7 on 2021-10-07 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210810_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='mobiles',
            name='information',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='information_mobile', to='client.information'),
            preserve_default=False,
        ),
    ]
